name = "coho-r2-explorer-dev"
compatibility_date = "2024-11-06"
main = "index.ts"
workers_dev = true

# (FJERNET assets = { ... })

[[r2_buckets]]
binding = "coho"
bucket_name = "coho-deliveries-dev"
preview_bucket_name = "coho-deliveries-dev"
