name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy R2-Explorer

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v5

      # 2. Setup Node 20
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # 3. Install dependencies for github-action
      - name: Install dependencies
        working-directory: packages/github-action
        run: |
          npm install
          npm install --save r2-explorer@latest

      # 4. Build R2-Explorer deployment package
      - name: Setup R2-Explorer
        env:
          R2EXPLORER_WORKER_NAME: ${{ vars.R2EXPLORER_WORKER_NAME }}
          R2EXPLORER_CONFIG: ${{ vars.R2EXPLORER_CONFIG }}
          R2EXPLORER_BUCKETS: ${{ vars.R2EXPLORER_BUCKETS }}
          R2EXPLORER_DOMAIN: ${{ vars.R2EXPLORER_DOMAIN }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: node packages/github-action/prepareDeploy.js

      # 5. Deploy til Cloudflare Workers
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "packages/github-action"
